gem 'quality_rake_tasks'
require 'quality_rake_tasks'

#---------------------------------------------------------------------------------------------------------------------------------
# Specification and description

module Project
  PrettyName = "escape"
  Name       = "escape"
  RubyForgeName = "quality-ext"
  Version    = "0.0.5" 
end

specification = Gem::Specification.new do |s|
  s.name    = Project::Name
  s.summary = "..."
  s.description = s.summary
  s.version = Project::Version
  s.author  = 'Tanaka Akira'
  s.homepage = "http://www.a-k-r.org/escape/"
  s.rubyforge_project = Project::Name
  s.platform = Gem::Platform::RUBY

  # Documentation
  s.has_rdoc = true
  s.extra_rdoc_files = ['Readme']
  s.rdoc_options << '--title' << Project::Name << '--main' << 'Readme' << '--line-numbers'

  # Files
  s.files = FileList['**/*.rb', 'bin/*', 'Readme'].exclude('ToDo').to_a
  s.test_files = Dir.glob('test/*.rb')
  s.require_path = "lib"
  #s.executables = "some_command"
end


#---------------------------------------------------------------------------------------------------------------------------------
# Tests

require 'rake/testtask'

task :default => :test
SharedTasks.normal_test_task

#---------------------------------------------------------------------------------------------------------------------------------
# Documentation



#---------------------------------------------------------------------------------------------------------------------------------
# Packaging

SharedTasks.package_task(specification)

#---------------------------------------------------------------------------------------------------------------------------------
# Publishing

SharedTasks.publish_task
SharedTasks.inc_version(__FILE__)

#---------------------------------------------------------------------------------------------------------------------------------
